# Generated by Django 5.2.6 on 2025-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polladas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partedelpollo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
