# Generated by Django 5.2.6 on 2025-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polladas', '0002_partedelpollo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_pedido',
            field=models.CharField(choices=[('recojo', 'Recojo en local'), ('delivery', 'Delivery')], default='recojo', max_length=10),
        ),
    ]
