# Generated by Django 5.2.6 on 2025-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polladas', '0003_cliente_tipo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
